# Generated by Django 4.2 on 2024-04-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "primary_breed",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "secondary_breed",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("is_mixed_breed", models.BooleanField(blank=True, null=True)),
                ("age", models.CharField(blank=True, max_length=1000, null=True)),
                ("sex", models.CharField(blank=True, max_length=1000, null=True)),
                ("size", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "coat_length",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("photo_url", models.CharField(blank=True, max_length=1000, null=True)),
                ("public_adoption_fee", models.FloatField(blank=True, null=True)),
                ("adoption_fee_waived", models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
