# Generated by Django 4.2 on 2024-04-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_pet"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="primary_color",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
