# Generated by Django 4.2 on 2024-04-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_pet_primary_color"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Link",
        ),
        migrations.AddField(
            model_name="pet",
            name="profile_url",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
