# Generated by Django 5.0.4 on 2025-09-16 23:50

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_delete_link_pet_profile_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pet', 'verbose_name_plural': 'Pets'},
        ),
        migrations.AddField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this record was created'),
        ),
        migrations.AddField(
            model_name='pet',
            name='scraped_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this pet data was scraped'),
        ),
        migrations.AddField(
            model_name='pet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last updated'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='adoption_fee_waived',
            field=models.BooleanField(default=False, help_text='Whether the adoption fee is waived'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(blank=True, help_text='Age of the pet', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='coat_length',
            field=models.CharField(blank=True, choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], help_text="Length of the pet's coat", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_mixed_breed',
            field=models.BooleanField(default=False, help_text='Whether the pet is a mixed breed'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(default='Unknown Pet', help_text="Pet's name", max_length=200),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo_url',
            field=models.URLField(blank=True, help_text="URL to the pet's primary photo", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='primary_breed',
            field=models.CharField(blank=True, help_text='Primary breed of the pet', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Primary color of the pet', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='profile_url',
            field=models.URLField(blank=True, help_text="URL to the pet's profile page", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='public_adoption_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Public adoption fee in USD', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='secondary_breed',
            field=models.CharField(blank=True, help_text='Secondary breed if mixed breed', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], help_text='Sex of the pet', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large')], help_text='Size of the pet', max_length=15, null=True),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['name'], name='website_pet_name_7a37d5_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['primary_breed'], name='website_pet_primary_85c5a2_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['sex'], name='website_pet_sex_f4d295_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['size'], name='website_pet_size_2082bd_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['created_at'], name='website_pet_created_ec9daa_idx'),
        ),
    ]
