# Generated by Django 5.0.4 on 2025-09-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_pet_options_pet_created_at_pet_scraped_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude coordinate of pet location', null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='location_city',
            field=models.CharField(blank=True, help_text='City where the pet is located', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='location_state',
            field=models.CharField(blank=True, help_text='State where the pet is located', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='location_zip',
            field=models.CharField(blank=True, help_text='ZIP code where the pet is located', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude coordinate of pet location', null=True),
        ),
    ]
